name: Generate Registry

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate
        run: |
          export STORE_BASE_PATH=$(pwd)
          pnpm --filter=xcm-chain-registry-builder build

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD; then
            echo "CHANGED=false" >> $GITHUB_OUTPUT
          else
            echo "CHANGED=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit files
        if: steps.check_changes.outputs.CHANGED == 'true'
        run: |
          MSG="Update xcm chain registry"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output || true
          git commit -m "${MSG:-Update}" || true
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.check_changes.outputs.CHANGED == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Trigger deploy
        if: steps.check_changes.outputs.CHANGED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run \
            deploy-stg.yml \
            --ref=main \
            --repo=ringecosystem/paralink \

